include $(GOROOT)/src/Make.inc

TARG=pooch_test

GOFILES=\
	dbg.go types.go parse.go newparse.go sqlite_caching.go\
	dbname.go backend.go staticserve.go htmlformat.go serve.go compat.go\
	multiserve.go\
	newparse_test.go

include $(GOROOT)/src/Make.cmd

staticservedeps = static-test.html list.css dlist.css int.js shortcut.js json.js calendar.css calendar.js fullcalendar.css fullcalendar.js jquery.js jquery-ui-custom.js cint.js cal.css
staticserve.go: $(staticservedeps)
	perl make-staticserve.pl $(staticservedeps) > staticserve.go

