include $(GOROOT)/src/Make.inc

TARG=pooch_test

GOFILES=\
	dbg.go types.go parse.go newparse.go\
	dbname.go backend.go staticserve.go htmlformat.go serve.go compat.go\
	multiserve.go\
	newparse_test.go

include $(GOROOT)/src/Make.cmd

staticservedeps = static/*
staticserve.go: $(staticservedeps)
	perl make-staticserve.pl $(staticservedeps) > staticserve.go

