include $(GOROOT)/src/Make.inc

TARG=parse

GOFILES=\
	dbg.go types.go backend.go luaint.go\
	parsetime.go tokenizer.go pureparser.go parserint.go\
	newparse_test.go

include $(GOROOT)/src/Make.cmd


